### ISSUE TITLE
Connects to postgres, but fails to run other commands

### ISSUE THREAD

**Issue by daneoshiga** [fastmonkeys/stellar#43]
After the fix in #31 I could connect to postgres databases, but now, after generating the stellar.yml, I can't run any command, all of them gives me database does not exist.

    For example:
    PostgreSQL: postgresql://localhost:5432/
    MySQL: mysql+pymysql://root@localhost/: postgresql://user@localhost:5432/database
    Please enter your project name (used internally, eg. sgro) [sgro]: 
    Wrote stellar.yaml

Then, running stellar snapshot (or any other):

    Traceback (...)
    sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  database "user" does not exist
    None None

**Comment by quantus** [comment]
This is related to issue #47. Everything should work after you run init again with the new version of stellar.
