### ISSUE TITLE
Impossible to restore a snapshot

### ISSUE THREAD

**Issue by Kraymer** [fastmonkeys/stellar#52]
All of a sudden my attempts to ``stellar restore`` end with

> Waiting for background process(1) to finish.....

Rebooting does not help.

### Workaround

So i installed stellar from sources after editing following code :  

    def is_copy_process_running(self, snapshot):
        if snapshot.worker_pid == 1:  
            return False
        return pid_exists(snapshot.worker_pid)

Which resulted in

> Background process missing, doing slow restore.
> Restoring database xxxxx
> Restore complete

and fixed my pb

**Comment by Frozenball** [comment]
Strange, what platform are you using?

**Comment by Kraymer** [comment]
Ubuntu 14.04

Used ``restore`` hundreds of times with no pb whatsoever before it happened.

**Comment by adisos** [comment]
I also facing this problem. I'm using stellar with docker:
https://gist.github.com/adisos/c6a3daf47abf76f465a7a21b93b2562f

@Kraymer How you installed from sources? Could you share tutorial how to build?
