### ISSUE TITLE
"pip install psycopg2" doesn't solve "Python library psycopg2 is required for PostreSQL support."

### ISSUE THREAD

**Issue by leonelgalan** [fastmonkeys/stellar#58]
I installed _psycopg2_ after being prompted to by stellar, but `stellar init` keeps failing even after installing _psycopg2_. I'm on a Mac and python was installed through Anaconda.

## Command Line

```sh
$ stellar init
Please enter the url for your database.

For example:
PostgreSQL: postgresql://localhost:5432/
MySQL: mysql+pymysql://root@localhost/: postgresql://localhost:5432/
Python library psycopg2 is required for PostreSQL support.
You can install it with pip:
pip install psycopg2

$ pip install psycopg2
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /Users/leonelgalan/anaconda/lib/python2.7/site-packages

$ which pip
/Users/leonelgalan/anaconda/bin/pip

$ which python
/Users/leonelgalan/anaconda/bin/python

$ stellar init
Please enter the url for your database.

For example:
PostgreSQL: postgresql://localhost:5432/
MySQL: mysql+pymysql://root@localhost/: postgresql://localhost:5432/
Python library psycopg2 is required for PostreSQL support.
You can install it with pip:
pip install psycopg2
```

**Comment by leonelgalan** [comment]
Sorry for the "noise", just typing questions helps finding a solution:

If you are using Anaconda, like me, install `psycopg2` using `conda install psycopg2` rather than `pip install psycopg2`

**Comment by ChristianVermeulen** [comment]
I'm having the same problem, however I'm not using anaconda, but just PIP, even installed it for this purpose...

![screenshot 2016-10-24 11 21 29](https://cloud.githubusercontent.com/assets/1062751/19640365/8d15a770-99dc-11e6-9100-ece05b077f7e.png)

**Comment by Frozenball** [comment]
There's a known issue that the "helpful" error message hides the underlying error, try doing the following:

````bash
python -c "import psycopg2"
````

**Comment by mszczepanczyk** [comment]
Had to install psycopg2 globally. Ubuntu: `apt-get install python-psycopg2`
