### ISSUE TITLE
[question] How can i specify the database to take a snapshot of?

### ISSUE THREAD

**Issue by shoad** [fastmonkeys/stellar#59]
Hi! An awesome lib! But i have a question. 

I can see the `tracked_databases: [mydbname]` line in the **stellar.yaml** file but can't figure out how to use this setting while taking a snapshot. I can modify the [mydbname] into [db_to_snapshot2] and i assume Stellar would look at the db_to_snapshot2 during the next snapshotting, but is there a way to specify db name while executing commands in shell? Something like `stellar snapshot db_to_snapshot2 snapshotname`

**Comment by Frozenball** [comment]
There's no general way to do that as Stellar is really designed for managing databases around projects. As a workaround you could create folders such as
````
project1/stellar.yaml
project2/stellar.yaml
project3/stellar.yaml
````

and then `cd` to the project and use Stellar from there.

**Comment by shoad** [comment]
Ok, got it. Thanks!
