### ISSUE TITLE
Trying to get this working on a Mac

### ISSUE THREAD

**Issue by tgreen7** [fastmonkeys/stellar#67]
I am getting the error 
```
ValueError: invalid literal for int() with base 10: '2 (Debian 10'
```
when calling stellar snapshot test

Postgres DB

**Comment by edsharp** [comment]
I have raised a PR that should fix this:

https://github.com/fastmonkeys/stellar/pull/68

**Comment by quantus** [comment]
The version 0.4.5 has been released a while ago, and it should contain fix for this issue.
